-- Migration: migrations/001_create_schema.sql
-- Description: Creates banks, pricing, and bills tables with constraints and foreign keys

-- 1. Banks Table
CREATE TABLE IF NOT EXISTS public.banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    template_path TEXT,
    bill_split TEXT DEFAULT 'bank',
    starting_invoice_no TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Pricing Table
CREATE TABLE IF NOT EXISTS public.pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES public.banks(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    price NUMERIC NOT NULL,
    column_key TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT pricing_bank_category_unique UNIQUE (bank_id, category)
);

-- 3. Bills Table
CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL REFERENCES public.banks(id) ON DELETE CASCADE,
    filename TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_pricing_bank_id ON public.pricing(bank_id);
CREATE INDEX IF NOT EXISTS idx_bills_bank_id ON public.bills(bank_id);
CREATE INDEX IF NOT EXISTS idx_bills_created_at ON public.bills(created_at DESC);
